--
--  UPDATE
--

-- UPDATE -> ENTER DATABASE
USE abscissa;

-- UPDATE -> TEMPORARILY DISABLE FK CHECKS
SET FOREIGN_KEY_CHECKS = 0;

-- UPDATE -> DROP EXISTING FOREIGN KEYS TO ALLOW COLUMN TYPE CHANGES
ALTER TABLE `USERS` DROP FOREIGN KEY `USERS_ibfk_1`;
ALTER TABLE `SESSIONS` DROP FOREIGN KEY `SESSIONS_ibfk_1`;
ALTER TABLE `PROBLEMS` DROP FOREIGN KEY `PROBLEMS_ibfk_1`,
    DROP FOREIGN KEY `PROBLEMS_ibfk_2`;
ALTER TABLE `RESOURCES` DROP FOREIGN KEY `RESOURCES_ibfk_1`;
ALTER TABLE `COMPLETED` DROP FOREIGN KEY `COMPLETED_ibfk_1`,
    DROP FOREIGN KEY `COMPLETED_ibfk_2`;

-- UPDATE -> ENABLE 0 MANUAL VALUE
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

-- UPDATE -> ORGANISATIONS UNSIGNED
ALTER TABLE `ORGANISATIONS`
    MODIFY `Oid` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Organisation ID.';

-- UPDATE -> USERS UNSIGNED
ALTER TABLE `USERS`
    MODIFY `Uid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier.',
    MODIFY `Oid` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'If the user is inside an organisation, be it not 0 but the ID of the organisation.',
    MODIFY `Urole` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Permissions of the user.';

-- UPDATE -> SESSIONS UNSIGNED
ALTER TABLE `SESSIONS`
    MODIFY `Uid` INT UNSIGNED NOT NULL COMMENT 'User linked to that session.';

-- UPDATE -> CONCEPTS UNSIGNED
ALTER TABLE `CONCEPTS`
    MODIFY `Kid` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Concept ID.';

-- UPDATE -> RESOURCES UNSIGNED
ALTER TABLE `RESOURCES`
    MODIFY `Rid` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID of the resource.',
    MODIFY `Kid` SMALLINT UNSIGNED NOT NULL COMMENT 'Concept the resource talks about.';

-- UPDATE -> PROBLEMS UNSIGNED
ALTER TABLE `PROBLEMS`
    MODIFY `Uid` INT UNSIGNED NOT NULL COMMENT 'Uid of the creator of the problem.',
    MODIFY `Kid` SMALLINT UNSIGNED NOT NULL COMMENT 'Concept identifier which the problem talks about.';

-- UPDATE -> COMPLETED UNSIGNED AND DEFAULT
ALTER TABLE `COMPLETED`
    MODIFY `Uid` INT UNSIGNED NOT NULL COMMENT 'Unique identifier of the user who completed the problem.',
    MODIFY `Ctime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When was the problem completed.';

-- UPDATE -> ANALYTICS TABLE
CREATE TABLE IF NOT EXISTS `ANALYTICS` (
  `Atime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Time when the action was registered',
  `Aaction` SMALLINT UNSIGNED NOT NULL COMMENT 'Action triggered'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- UPDATE -> DEFAULT USER
UPDATE `USERS` SET `Urole` = 255 WHERE `Uid` = 1;

-- UPDATE -> RECREATE FOREIGN KEYS WITH UPDATED COLUMN TYPES
ALTER TABLE `USERS`
    ADD CONSTRAINT `USERS_ibfk_1` FOREIGN KEY (`Oid`) REFERENCES `ORGANISATIONS` (`Oid`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `SESSIONS`
    ADD CONSTRAINT `SESSIONS_ibfk_1` FOREIGN KEY (`Uid`) REFERENCES `USERS` (`Uid`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PROBLEMS`
    ADD CONSTRAINT `PROBLEMS_ibfk_1` FOREIGN KEY (`Uid`) REFERENCES `USERS` (`Uid`) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT `PROBLEMS_ibfk_2` FOREIGN KEY (`Kid`) REFERENCES `CONCEPTS` (`Kid`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `RESOURCES`
    ADD CONSTRAINT `RESOURCES_ibfk_1` FOREIGN KEY (`Kid`) REFERENCES `CONCEPTS` (`Kid`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `COMPLETED`
    ADD CONSTRAINT `COMPLETED_ibfk_1` FOREIGN KEY (`Uid`) REFERENCES `USERS` (`Uid`) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT `COMPLETED_ibfk_2` FOREIGN KEY (`Pid`) REFERENCES `PROBLEMS` (`Pid`) ON DELETE CASCADE ON UPDATE CASCADE;

-- UPDATE -> RE-ENABLE FK CHECKS
SET FOREIGN_KEY_CHECKS = 1;